#40 add text validation
Team-Maple-Leaf/MapleJudgePlatform pull request #42
Opened 2022-10-16 02:03 UTC by juyonLee00

<img width="876" alt="image" src="https://user-images.githubusercontent.com/48848525/196014370-066a3b4c-f39f-4da1-86ab-585dda0647ee.png">

코드가 비었을 경우 위 사진과 같이 경고문이 뜨면서 다음 페이지로 넘어가지 않도록 처리하였습니다.

2022-10-16 12:55 UTC, level120 requested changes
이 페이지를 참고하여 mitt의 emitter를 사용하지 않는 이벤트는 이벤트를 명시적으로 표현해주세요.
나중에 외부에서 이벤트를 수신해야 할 경우 핸들링하기 쉽고 의도하지 않은 오류를 방지할 수 있어요.
https://github.com/Team-Maple-Leaf/MapleJudgePlatform/blob/main/src/components/AppNav.vue#L47

2022-10-16 12:55 UTC, level120 commented on src/pages/ProblemSubmitView.vue
> +const languageList = ["c", "java"];
```suggestion
const languageList: string[] = ["c", "java"];
```

2022-10-16 12:55 UTC, level120 commented on src/pages/ProblemSubmitView.vue
> +const selectedLanguage = ref(languageList[0] as string);
```suggestion
const selectedLanguage = ref(languageList[0]);
```

2022-10-16 12:55 UTC, level120 commented on src/pages/ProblemSubmitView.vue
> +]);
음.... 반환값이 boolean 처럼 보이는데 맞나요?

2022-10-16 12:55 UTC, level120 commented on src/pages/ProblemSubmitView.vue
> +}
```suggestion
const gotoResultPage = async() => {
  const result = await form.value.validate();
  
  if (result.valid) {
    router.push("/result/" + problemNo);
  }
};
```

2022-10-16 13:31 UTC, juyonLee00 commented on src/pages/ProblemSubmitView.vue
> +]);
넵 맞습니다! 그것도 수정해 두겠습니다

2022-10-16 14:18 UTC, level120 commented on src/pages/ProblemSubmitView.vue
> +]);
마음에 들진 않는데.. Vuetify 문서를 보니 이렇게 작성하도록 가이드하고 있네요..
그냥 유지하시죠.

2022-10-17 14:48 UTC, level120 approved these changes

2022-10-17 14:55 UTC, Supernovaysi approved these changes

2022-10-18 14:04 UTC, merged